### ISSUE TITLE
can't configure attribute-based fencing topology

### ISSUE THREAD

**Issue by aspiers** [ClusterLabs/crmsh#110]
```
root@d52-54-02-77-77-02:~ # crm configure
crm(live)configure# fencing_topology attr:OpenStack-role=compute stonith-libvirt,fence-nova
crm(live)configure# There are changes pending. Do you want to commit them (y/n)? y
Traceback (most recent call last):
  File "/usr/sbin/crm", line 54, in <module>
    rc = main.run()
  File "/usr/lib/python2.7/site-packages/crmsh/main.py", line 351, in run
    return main_input_loop(context, user_args)
  File "/usr/lib/python2.7/site-packages/crmsh/main.py", line 253, in main_input_loop
    context.quit(rc)
  File "/usr/lib/python2.7/site-packages/crmsh/ui_context.py", line 319, in quit
    ok = self.current_level().end_game()
  File "/usr/lib/python2.7/site-packages/crmsh/ui_configure.py", line 859, in end_game
    ok = self._commit()
  File "/usr/lib/python2.7/site-packages/crmsh/ui_configure.py", line 584, in _commit
    self._verify(mkset_obj("xml", "changed"), mkset_obj("xml"))
  File "/usr/lib/python2.7/site-packages/crmsh/ui_configure.py", line 430, in _verify
    rc2 = set_obj_semantic.semantic_check(set_obj_all)
  File "/usr/lib/python2.7/site-packages/crmsh/cibconfig.py", line 494, in semantic_check
    rc |= obj.check_sanity()
  File "/usr/lib/python2.7/site-packages/crmsh/cibconfig.py", line 2017, in check_sanity
    if target.lower() not in [id.lower() for id in cib_factory.node_id_list()]:
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by aspiers** [comment]
Verified as working via https://build.opensuse.org/package/rdiff/home:aspiers:branches:network:ha-clustering:Factory/crmsh?linkrev=base&rev=2
