### ISSUE TITLE
AttributeError: module 'parallax' has no attribute 'run'

### ISSUE THREAD

**Issue by storcium** [ClusterLabs/crmsh#1118]
Trying to use crmsh 4.4.0 on RHEL 8.7 produces the error in the subject line.  Looks like parallax 1.0.6 has no run attribute, the stack is below.  Going down to v4.1 of crmsh solves the problem, but it appears that v4.4.0 has been updated without version change.

INFO: crmsh version is newer than its configuration. Configuration upgrade is needed.
Traceback (most recent call last):
  File "/usr/local/bin/crm", line 52, in <module>
    rc = main.run()
  File "/usr/local/lib/python3.6/site-packages/crmsh/main.py", line 375, in run
    upgradeutil.upgrade_if_needed()
  File "/usr/local/lib/python3.6/site-packages/crmsh/upgradeutil.py", line 120, in upgrade_if_needed
    if not _is_cluster_target_seq_consistent(nodes):
  File "/usr/local/lib/python3.6/site-packages/crmsh/upgradeutil.py", line 74, in _is_cluster_target_seq_consistent
    results = list(crmsh.parallax.parallax_run(nodes, cmd).values())
  File "/usr/local/lib/python3.6/site-packages/crmsh/parallax.py", line 131, in parallax_run
    return p.run()
  File "/usr/local/lib/python3.6/site-packages/crmsh/parallax.py", line 73, in run
    return parallax.run(
AttributeError: module 'parallax' has no attribute 'run'

**Comment by liangxin1300** [comment]
Hi @storcium 
Please try to use the latest version of parallax https://github.com/krig/parallax/tags

**Comment by zzhou1** [comment]
Hum, crmsh.spec could improve

Requires:       python3-parallax >= 1.0.8

**Comment by storcium** [comment]
Much appreciated!

--
Alex
