### ISSUE TITLE
`crm init qdevice` fails when the cluster is upgraded from crmsh 4.4

### ISSUE THREAD

**Issue by nicholasyang2022** [ClusterLabs/crmsh#1157]
1. initialize a cluster with crmsh 4.4, as root
2. upgrade crmsh to master
3. run `sudo crm cluster init qdevice --qnetd-hostname qnetd-node -y` as a non-root user

    ```
    INFO: Loading "default" profile from /etc/crm/profiles.yml
    WARNING: chronyd.service is not configured to start at system boot.
    INFO: Configure Qdevice/Qnetd:
    Traceback (most recent call last):
      File "/usr/sbin/crm", line 52, in <module>
        rc = main.run()
      File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 369, in run
        return main_input_loop(context, user_args)
      File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 247, in main_input_loop
        rc = handle_noninteractive_use(context, user_args)
      File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 204, in handle_noninteractive_use
        if context.run(' '.join(l)):
      File "/usr/lib/python3.6/site-packages/crmsh/ui_context.py", line 86, in run
        rv = self.execute_command() is not False
      File "/usr/lib/python3.6/site-packages/crmsh/ui_context.py", line 271, in execute_command
        rv = self.command_info.function(*arglist)
      File "/usr/lib/python3.6/site-packages/crmsh/ui_cluster.py", line 372, in do_init
        bootstrap.bootstrap_init(boot_context)
      File "/usr/lib/python3.6/site-packages/crmsh/bootstrap.py", line 2368, in bootstrap_init
        globals()["init_" + stage]()
      File "/usr/lib/python3.6/site-packages/crmsh/bootstrap.py", line 1635, in init_qdevice
        local_user = utils.user_of(utils.this_node())
      File "/usr/lib/python3.6/site-packages/crmsh/utils.py", line 207, in user_of
        return _user_of_host_instance.user_of(host)
      File "/usr/lib/python3.6/site-packages/crmsh/utils.py", line 124, in user_of
        raise self.UserNotFoundError
    crmsh.utils.UserNotFoundError
    ```

**Comment by liangxin1300** [comment]
Fixed in #1158
