### ISSUE TITLE
commit force throws an error

### ISSUE THREAD

**Issue by bogdando** [ClusterLabs/crmsh#120]
With crmsh v. 2.2.0-1,
```
# crm configure
crm(live)configure# property no-quorum-policy=ignore
crm(live)configure# commit force
Traceback (most recent call last):
  File "/usr/sbin/crm", line 54, in <module>
    rc = main.run()
  File "/usr/lib/python2.7/dist-packages/crmsh/main.py", line 351, in run
    return main_input_loop(context, user_args)
  File "/usr/lib/python2.7/dist-packages/crmsh/main.py", line 255, in main_input_loop
    if not context.run(inp):
  File "/usr/lib/python2.7/dist-packages/crmsh/ui_context.py", line 75, in run
    rv = self.execute_command() is not False
  File "/usr/lib/python2.7/dist-packages/crmsh/ui_context.py", line 245, in execute_command
    rv = self.command_info.function(*arglist)
  File "/usr/lib/python2.7/dist-packages/crmsh/ui_configure.py", line 648, in do_commit
    return self._commit(force=force, replace=replace)
  File "/usr/lib/python2.7/dist-packages/crmsh/ui_configure.py", line 614, in _commit
    syntax_err(('configure.commit', force))
  File "/usr/lib/python2.7/dist-packages/crmsh/msg.py", line 216, in syntax_err
    err += " parsing '%s'" % (' '.join(s))
TypeError: sequence item 1: expected string, bool found
```

While just "commit" works

**Comment by krig** [comment]
Thanks, fixed in master
