### ISSUE TITLE
python3.8 changes ast elements breaking unittests

### ISSUE THREAD

**Issue by cpaelzer** [ClusterLabs/crmsh#518]
Hi,
in the Ubuntu tests `crmsh` recently showed up when we switched to python 3.8.
=> [Full test](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal/focal/amd64/c/crmsh/20200125_054659_c3456@/log.gz)

In particular I found this trace:
```
Test when expressions ... ERROR
...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 222, in _eval
    handler = self.nodes[type(node)]
KeyError: <class '_ast.Constant'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/crmsh/scripts.py", line 134, in __str__
    return str(minieval(inp, lenv)).lower()
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 360, in minieval
    return SimpleEval(env).evaluate(expr)
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 216, in evaluate
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 227, in _eval
    return handler(node)
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 270, in _eval_compare
    right = self._eval(comp)
  File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 224, in _eval
    raise FeatureNotAvailable("Sorry, {0} is not available in this "
crmsh.minieval.FeatureNotAvailable: Sorry, Constant is not available in this evaluator
```

Search-Foo brought up [this fix](https://github.com/mommothazaz123/simpleeval/commit/65ab6c510563a490f22b7307b7370457cd839afe) in a different project. Inspired by that (but not really knowing what I do) I came up for crmsh with this fix:

```
--- /usr/lib/python3/dist-packages/crmsh/minieval.py.orig       2020-01-28 08:26:07.808589457 +0000
+++ /usr/lib/python3/dist-packages/crmsh/minieval.py    2020-01-28 08:42:16.667661442 +0000
@@ -200,10 +200,14 @@
 
         # py3k stuff:
         if hasattr(ast, 'NameConstant'):
-            self.nodes[ast.NameConstant] = self._eval_nameconstant
+            self.nodes[ast.NameConstant] = self._eval_constant
         elif isinstance(self.names, dict) and "None" not in self.names:
             self.names["None"] = None
 
+        # py3.8 uses ast.Constant instead of ast.Num, ast.Str, ast.NameConstant
+        if hasattr(ast, 'Constant'):
+            self.nodes[ast.Constant] = self._eval_constant
+
     def evaluate(self, expr):
         """ evaluate an expresssion, using the operators, functions and
             names previously set up. """
@@ -239,7 +243,10 @@
         return node.s
 
     @staticmethod
-    def _eval_nameconstant(node):
+    def _eval_constant(node):
+        if hasattr(node.value, '__len__') and len(node.value) > MAX_STRING_LENGTH:
+            raise IterableTooLong("Literal in statement is too long!"
+                                  " ({0}, when {1} is max)".format(len(node.value), MAX_STRING_LENGTH))
         return node.value
 
     def _eval_unaryop(self, node):
```

That gets the tests passing with python 3.8:

```
Ran 258 tests in 9.582s
OK

```

I'd be glad someone more _pythonic_ and more into the `crmsh` details could double check and apply if it makes sense to you.

**Comment by liangxin1300** [comment]
Hi @cpaelzer,
Thanks for using crmsh!
That looks good to me!
Could you please create a pull request? Thanks!

**Comment by cpaelzer** [comment]
Sure @liangxin1300 with the renewed confidence by your comment I can do a PR ...

**Comment by cpaelzer** [comment]
For the PR I tried to stay inside the 80 char limit which makes the lines somewhat odd.
But since everything else in the file followed that I thought it is better that way.
